name: Simple Local

on: push

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - uses: actions/checkout@v3
      - run: node --version
      - run: npm --version
      - run: cd lab02_1 && npm install
      - run: cd lab02_1 && npm install --save moment
      - run: cd lab02_1 && node src/app.js